"""add image_documents table

Revision ID: 7c4c92edc740
Revises: ab93ae34ffa1
Create Date: 2026-03-10 03:37:19.549778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c4c92edc740'
down_revision: Union[str, Sequence[str], None] = 'ab93ae34ffa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('blog_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_documents_blog_id'), 'image_documents', ['blog_id'], unique=False)
    op.drop_column('blog_posts', 'content_type')
    op.drop_column('blog_posts', 'rich_content')
    op.alter_column('pdf_documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdf_documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('blog_posts', sa.Column('rich_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('blog_posts', sa.Column('content_type', sa.VARCHAR(), server_default=sa.text("'plain'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_image_documents_blog_id'), table_name='image_documents')
    op.drop_table('image_documents')
    # ### end Alembic commands ###
