"""add created_at to memberships

Revision ID: fbbf5c6a5238
Revises: fd827c725a3b
Create Date: 2026-03-04 11:03:11.195970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbbf5c6a5238'
down_revision: Union[str, Sequence[str], None] = 'fd827c725a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_blog_posts_org_created_at', 'blog_posts', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_org_id'), 'blog_posts', ['org_id'], unique=False)
    op.drop_constraint(op.f('blog_posts_org_id_fkey'), 'blog_posts', type_='foreignkey')
    op.create_foreign_key(None, 'blog_posts', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.add_column('memberships', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_memberships_org_id'), 'memberships', ['org_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index('ix_memberships_user_org', 'memberships', ['user_id', 'org_id'], unique=False)
    op.create_unique_constraint('uq_membership_user_org', 'memberships', ['user_id', 'org_id'])
    op.drop_constraint(op.f('memberships_user_id_fkey'), 'memberships', type_='foreignkey')
    op.drop_constraint(op.f('memberships_org_id_fkey'), 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'memberships', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.create_foreign_key(op.f('memberships_org_id_fkey'), 'memberships', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(op.f('memberships_user_id_fkey'), 'memberships', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_membership_user_org', 'memberships', type_='unique')
    op.drop_index('ix_memberships_user_org', table_name='memberships')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_org_id'), table_name='memberships')
    op.drop_column('memberships', 'created_at')
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.create_foreign_key(op.f('blog_posts_org_id_fkey'), 'blog_posts', 'organizations', ['org_id'], ['id'])
    op.drop_index(op.f('ix_blog_posts_org_id'), table_name='blog_posts')
    op.drop_index('ix_blog_posts_org_created_at', table_name='blog_posts')
    op.alter_column('blog_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
